# Generated by Django 6.0.3 on 2026-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfachallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('change_password', 'Change Password'), ('change_email', 'Change Email'), ('delete_account', 'Delete Account')], max_length=50),
        ),
    ]
